# Percolator Surfpool Configuration
# This manifest defines the testing environment for Percolator programs

[project]
name = "percolator"
version = "0.1.0"
authors = ["Percolator Team"]

[programs]
router = "programs/router"
slab = "programs/slab"

[runbooks]
# Basic connectivity test
test_basic = ".surfpool/runbooks/test_basic.tx"

# Custom test runbooks (TODO)
# test_initialization = ".surfpool/runbooks/test_initialization.tx"
# test_reserve_commit = ".surfpool/runbooks/test_reserve_commit.tx"
# test_portfolio = ".surfpool/runbooks/test_portfolio.tx"

[settings]
rpc_url = "https://api.mainnet-beta.solana.com"
slot_time = 400
airdrop_amount = 10_000_000_000_000  # 10M SOL for testing
